### ISSUE TITLE
title ne

### ISSUE THREAD

**Issue by azhoang** [azhoang/azhoang.github.io#1]
# GFM

## Autolink literals

www.example.com, https://example.com, and contact@example.com.

## Footnote

A note[^1]

[^1]: Big note.

## Strikethrough

~one~ or ~~two~~ tildes.

![image](https://user-images.githubusercontent.com/113039729/192222139-926c0ed1-a176-4ab9-8ede-f503e2c7996d.png)

```js
export default function App() {
  return (
    <article class="markdown-body">
      <ReactMarkdown children={markdown} remarkPlugins={[remarkGfm]} />
    </article>
  );
}
```

## Table

|a|bdfsdfsdf|c|d|
|-  |-  |-  |-  |
|c|csdfsdf|caaaaa|c|

## Tasklist

* [x] done
* [ ] to do
```bash
git status
```

This is to display the 
`$$c = \pm\sqrt{a^2 + b^2}$$`
 in one line

```KaTeX
c = \pm\sqrt{a^2 + b^2}
```

> fffaa dasd as

asdasdasd ?
A note[^1]

[^1]: Big note.

## Strikethrough

~one~ or ~~two~~ tildes.

```js
export default function App() {
  return (
    <article class="markdown-body">
      <ReactMarkdown children={markdown} remarkPlugins={[remarkGfm]} />
    </article>
  );
}
```

## Table

|a|bdfsdfsdf|c|d|
|-  |-  |-  |-  |
|c|csdfsdf|caaaaa|c|

## Tasklist

* [x] done
* [ ] to do
```bash
git status
```

This is to display the 
`$$c = \pm\sqrt{a^2 + b^2}$$`
 in one line

```KaTeX
c = \pm\sqrt{a^2 + b^2}
```

> fffaa dasd as

asdasdasd ?

**Comment by azhoang** [comment]
1111111

**Comment by hhoangg** [comment]
> > 1111111
> 
> asdasda dasd

? test

**Comment by hhoangg** [comment]
[gggasda das dasd](https://github.com/azhoang/azhoang.github.io/issues/1#issuecomment-1255062883)

- [ ] asdasdasd
- [ ] asdasdasda
- [ ] sdasdfsdfs
- [ ] s fsd
- [ ] f sdfsdfsdf

**Comment by azhoang** [comment]
> [gggasda das dasd](https://github.com/azhoang/azhoang.github.io/issues/1#issuecomment-1255062883)
> 
> * [ ]  asdasdasd
> * [ ]  asdasdasda
> * [ ]  sdasdfsdfs
> * [ ]  s fsd
> * [ ]  f sdfsdfsdf

sao do ban oi

**Comment by azhoang** [comment]
Me too
